/*
auto-generated by: https://github.com/react-spring/gltfjsx
author: ricksticky (https://sketchfab.com/ricksticky)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/pistosaur-animated-773667575a264c7baa4ec404115a044b
title: Pistosaur Animated
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, '/assets/pistosaur/scene.gltf')

  // const actions = useRef()
  // const [mixer] = useState(() => new THREE.AnimationMixer())
  // useFrame((state, delta) => mixer.update(delta))
  // useEffect(() => {
  //   actions.current = {
  //     'Take 001': mixer.clipAction(animations[0], group.current),
  //   }
  //   return () => animations.forEach((clip) => mixer.uncacheClip(clip))
  // }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes._rootJoint} />
          <group position={[0, 1.42, 5.25]} scale={[20.22, 20.22, 20.22]} />
          <skinnedMesh
            material={materials.blinn4}
            geometry={nodes.Total_BodySurface_blinn4_0.geometry}
            skeleton={nodes.Total_BodySurface_blinn4_0.skeleton}
          />
          <skinnedMesh
            material={materials.blinn3}
            geometry={nodes.Tongue_blinn3_0.geometry}
            skeleton={nodes.Tongue_blinn3_0.skeleton}
          />
        </group>
      </group>
    </group>
  )
}
